version: "3.9"
services:
  pluto-app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    networks:
      - pluto-network
    ports:
      - "3000:3000"
    image: pluto-app
    environment:
      - DATABASE_URL=$DATABASE_URL
      - AUTH0_SECRET=$AUTH0_SECRET
      - APP_BASE_URL=$APP_BASE_URL
      - AUTH0_DOMAIN=$AUTH0_DOMAIN
      - AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET

networks:
  pluto-network:
    name: "Pluto Network"